# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy dependency specification
COPY pyproject.toml .

# Install dependencies
RUN pip install --no-cache-dir fastmcp>=2.10.5 python-dotenv>=1.0.0 httpx>=0.24.0 pytz>=2025.2

# Copy application files
COPY email-schedule-send-mcp-server.py .
# (Optionally copy .env if present)

# Default command
CMD ["python", "email-schedule-send-mcp-server.py"]
